# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:14.19.0

clone:
  lfs: true
pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run test
            - npm run webpack:dev
  custom:
    Development Flow:
     - variables:
        - name: CODE_VERSION
     - step:
        name: Build & Deploy & Activate to Development
        deployment: Development
        caches:
            - node
        script:
            - cd build
            - npm install
            - ./node_modules/.bin/grunt build --target=$TARGET
            - ./node_modules/.bin/grunt importSite --target=$TARGET
            - ./node_modules/.bin/grunt upload --target=$TARGET
            - ./node_modules/.bin/grunt activate --target=$TARGET
    Staging Flow:
      - variables:
        - name: CODE_VERSION
      - step:
          name: Build & Deploy & Activate to Staging
          deployment: Staging
          caches:
              - node
          script:
              - cd build
              - npm install
              - ./node_modules/.bin/grunt build --target=$TARGET
              - ./node_modules/.bin/grunt upload --target=$TARGET